spring.main.allow-bean-definition-overriding: true
keycloak:
  enabled: true
  auth-server-url: http://keycloak.ferret.space:8080/auth
  realm: ferret-space
  bearer-only: true
  resource: ferret-space-backend
#  security-constraints:
#  - authRoles:
#    - admin
#    securityCollections:
#    - patterns:
#      - /admin/*